server:
  port: 9090
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: 2211223
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

myapplication:
  myinfo:
    info: "This is an information"
    title: "This is a title"